services:
  # Backend API Server
  - type: web
    name: chinese-tutor-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://chinese-tutor-frontend.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: chinese-tutor-frontend
    env: static
    plan: free
    buildCommand: echo "No build needed for static site"
    startCommand: echo "Static site deployed"
    staticPublishPath: ./public
    envVars:
      - key: BACKEND_URL
        value: https://chinese-tutor-backend.onrender.com
